### ISSUE TITLE
Conflict between AoV and Wizardry

### ISSUE THREAD

**Issue by Tyrius1** [Tamaized/AoV#115]
https://minecraft.curseforge.com/projects/dogma Conflict between AoV and Wizardry causing Wizardry codex to not load properly. When removing AoV codex works as intended.

**Comment by murapix** [comment]
This has been reported a couple times in TeamWizardry/Wizardry#223

**Comment by Tamaized** [comment]
My initial guess was a stencil buffer conflict but that doesn't seem to be the case unless i'm mistaken. Other than that I have no idea where the issue is as it's a bit difficult for me to navigate their codebase across the libs and such (and it's written in kotlin bleh)

if someone wants to go digging feel free.

**Comment by Tamaized** [comment]
Found the issue, it was indeed my first hunch, a stencil buffer conflict.

Working on a fix~

**Comment by Tamaized** [comment]
Should be fixed in version 0.11.4

leaving this open until i merge the fix into my 1.13 branch
